kind: Job
apiVersion: batch/v1
metadata:
  name: etcd-backup
  namespace: openshift-etcd
  labels:
    app: etcd-backup
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 6
  template:
    metadata:
      name: etcd-backup
    spec:
      restartPolicy: Never
      serviceAccountName: etcd-backup
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - name: backup
          image: image-registry.openshift-image-registry.svc:5000/openshift-etcd/etcd-backup:latest
          command:
          	- "/usr/local/bin/backup.sh"
          args: []
          workingDir: /backup
          resources: {}
          volumeMounts:
            - name: storage
              mountPath: /backup
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      serviceAccount: etcd-backup
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: etcd-backup
      dnsPolicy: ClusterFirst

